# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from typing import Literal
from datetime import datetime
    
class Ui_Interface(QtWidgets.QMainWindow):
    @property
    def start_date(self) -> datetime:
        date = self.__start_date
        if self.__end_date:
            if self.__end_date < self.__start_date:
                date = self.__end_date
        return datetime(date.year(), date.month(), date.day())
    
    @property
    def end_date(self) -> datetime|None:
        date:QtCore.QDate|None = self.__end_date
        if self.__end_date:
            if self.__end_date < self.__start_date:
                date = self.__start_date
            
        
        if isinstance(date, QtCore.QDate):
            return datetime(date.year(), date.month(), date.day())
        return None
    
    def __init__(self, *, nav:object=object(), version:str="Beta"):
        self.__version:str = version
        self.__nav = nav
        
        super().__init__()
        
        self.setObjectName("Interface")
        
        self.resize(800, 500)
        self.setAnimated(True)
        
        self.setMaximumSize(self.size())
        self.setMinimumSize(self.size())
    
        self.Central = QtWidgets.QWidget(self)
        self.Central.setObjectName("Central")
        
        self.Telas = QtWidgets.QStackedWidget(self.Central)
        self.Telas.setGeometry(5,5, self.width() -10, self.height() - 30)
        self.Telas.setObjectName("Telas")
        self.Telas.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.Telas.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
                
        # self.Tela0 = QtWidgets.QWidget()
        # self.Tela0.setObjectName("Tela0")
        
        #self.Telas.addWidget(self.Tela0)
        
        self.Tela0 = QtWidgets.QWidget()
        self.Tela0.setObjectName("Tela1")

        # linha 1
        
        self.Tela0_label_moviDiariaTitulo = QtWidgets.QLabel(self.Tela0)
        self.Tela0_label_moviDiariaTitulo.setGeometry(QtCore.QRect(50,25,600,25))
        self.Tela0_label_moviDiariaTitulo.setObjectName("Tela0_label_moviDiariaTitulo")
        
        
        self.Tela0_bt_moviDiaria = QtWidgets.QToolButton(self.Tela0)
        self.Tela0_bt_moviDiaria.setGeometry(QtCore.QRect(10,50,25,25))
        self.Tela0_bt_moviDiaria.setObjectName("Tela0_bt_moviDiaria")
        #self.Tela0_bt_moviDiaria.clicked.connect(self.procurar_file)
        
        self.Tela0_text_moviDiaria = QtWidgets.QLineEdit(self.Tela0)
        self.Tela0_text_moviDiaria.setGeometry(QtCore.QRect(50,50,600,25))
        self.Tela0_text_moviDiaria.setObjectName("Tela0_text_moviDiaria")
        self.Tela0_text_moviDiaria.setReadOnly(True)
        ##
        
        # linha 2
        
        self.Tela0_label_lancamentoTitulo = QtWidgets.QLabel(self.Tela0)
        self.Tela0_label_lancamentoTitulo.setGeometry(QtCore.QRect(50,100,600,25))
        self.Tela0_label_lancamentoTitulo.setObjectName("Tela0_label_lancamentoTitulo")
        
        
        self.Tela0_bt_lancamento = QtWidgets.QToolButton(self.Tela0)
        self.Tela0_bt_lancamento.setGeometry(QtCore.QRect(10,125,25,25))
        self.Tela0_bt_lancamento.setObjectName("Tela0_bt_lancamento")
        #self.Tela0_bt_moviDiaria.clicked.connect(self.procurar_file)
        
        self.Tela0_text_lancamento = QtWidgets.QLineEdit(self.Tela0)
        self.Tela0_text_lancamento.setGeometry(QtCore.QRect(50,125,600,25))
        self.Tela0_text_lancamento.setObjectName("Tela0_text_lancamento")
        self.Tela0_text_lancamento.setReadOnly(True)
        ##
        
        # linha 3
        
        self.Tela0_calendar = QtWidgets.QCalendarWidget(self.Tela0)
        self.Tela0_calendar.setGeometry(QtCore.QRect(50,175,500,225))
        self.Tela0_calendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.Tela0_calendar.setGridVisible(True)
        self.Tela0_calendar.clicked[QtCore.QDate].connect(self.select_date)
        
        self.__start_date = self.Tela0_calendar.selectedDate()
        self.__end_date = None

        self.select_date(self.__start_date)
        self.select_date(self.__start_date)
        
        #linha 4
        
        self.Tela0_bt_iniciarNavegador = QtWidgets.QPushButton(self.Tela0)
        self.Tela0_bt_iniciarNavegador.setGeometry(QtCore.QRect(10,425,150,25))
        self.Tela0_bt_iniciarNavegador.setObjectName("Tela0_bt_iniciar")
        
        self.Tela0_bt_iniciarExtract = QtWidgets.QPushButton(self.Tela0)
        self.Tela0_bt_iniciarExtract.setGeometry(QtCore.QRect(175,425,150,25))
        self.Tela0_bt_iniciarExtract.setObjectName("Tela0_bt_iniciarExtract")
        self.Tela0_bt_iniciarExtract.setVisible(False)
        
        self.Tela0_bt_transformar = QtWidgets.QPushButton(self.Tela0)
        self.Tela0_bt_transformar.setGeometry(QtCore.QRect(500,425,150,25))
        self.Tela0_bt_transformar.setObjectName("Tela0_bt_transformar")
        self.Tela0_bt_transformar.setText("Teste")
        self.Tela0_bt_transformar.setVisible(True)
        #self.Tela0_bt_transformar.clicked.connect(self.test)
        
        self.Telas.addWidget(self.Tela0)
        self.Telas.setCurrentIndex(0)
        
        self.setCentralWidget(self.Central)
                
        # self.menuBar = QtWidgets.QMenuBar(self)
        # self.menuBar.setGeometry(QtCore.QRect(0, 0, 794, 21))
        # self.menuBar.setObjectName("menuBar")
        
        # self.menuFile = QtWidgets.QMenu(self.menuBar)
        # self.menuFile.setObjectName("menuFile")
        
        # self.menuNew = QtWidgets.QMenu(self.menuFile)
        # self.menuNew.setObjectName("menuNew")
        
        # self.menuHelp = QtWidgets.QMenu(self.menuBar)
        # self.menuHelp.setObjectName("menuHelp")
        
        # self.setMenuBar(self.menuBar)
        
        # self.actionQuit = QtWidgets.QAction(self)
        # self.actionQuit.setObjectName("actionQuit")
        
        # self.actionFile = QtWidgets.QAction(self)
        # self.actionFile.setObjectName("actionFile")
        
        # self.actionAbout = QtWidgets.QAction(self)
        # self.actionAbout.setObjectName("actionAbout")
        
        # self.menuNew.addSeparator()
        # self.menuNew.addAction(self.actionFile)
        
        # self.menuFile.addAction(self.menuNew.menuAction())
        # self.menuFile.addSeparator()
        # self.menuFile.addAction(self.actionQuit)
        
        # self.menuHelp.addAction(self.actionAbout)
        
        # self.menuBar.addAction(self.menuFile.menuAction())
        # self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)
        
    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Interface", f"Informe de Rendimentos TRM | Versão: {self.__version}"))
        
        self.Tela0_label_moviDiariaTitulo.setText(_translate("Interface", "Caminho da planilha da Movimentação Diaria:"))
        self.Tela0_bt_moviDiaria.setText(_translate("Interface", "..."))
        self.Tela0_text_moviDiaria.setText(_translate("Interface", "Vazio"))
        
        self.Tela0_label_lancamentoTitulo.setText(_translate("Interface", "Caminho da planilha da Lançamento - TRM:"))
        self.Tela0_bt_lancamento.setText(_translate("Interface", "..."))
        self.Tela0_text_lancamento.setText(_translate("Interface", "Vazio"))
        
        self.Tela0_bt_iniciarNavegador.setText(_translate("Interface", "Abrir Navegador"))
        self.Tela0_bt_iniciarExtract.setText(_translate("Interface", "Iniciar Extração"))
        self.Tela0_bt_transformar.setText(_translate("Interface", "Transformar Dados"))
        
        # self.menuFile.setTitle(_translate("Interface", "Arquivos"))
        # self.menuNew.setTitle(_translate("Interface", "New"))
        # self.menuHelp.setTitle(_translate("Interface", "Help"))
        # self.actionQuit.setText(_translate("Interface", "Quit"))
        # self.actionFile.setText(_translate("Interface", "File"))
        # self.actionAbout.setText(_translate("Interface", "About"))
        
    def procurar_file(self) -> str:
        path = QtWidgets.QFileDialog.getOpenFileName()[0]
        if path:
            return path
        else:
            return ""

        raise Exception(f"'{path=} não encontrado")
    
    def alerta(self, *, title:Literal['Alerta', 'Error', 'Concluido'], description:str) -> None:
        alert = QtWidgets.QMessageBox()
        alert.setWindowTitle(title)
        alert.setText(description)
        alert.setIcon(QtWidgets.QMessageBox.Icon.Warning)
        alert.setStandardButtons(QtWidgets.QMessageBox.StandardButton.Ok)
        alert.exec_()
    
    def closeEvent(self, a0):
        try:
            self.__nav.exit() #type: ignore
        except:
            pass
        if a0:
            a0.accept()
            
    def select_date(self, date):
        if not self.__start_date: #type: ignore
            self.__start_date = date
            self.highlight_date(self.__start_date, QtGui.QColor("green"))
            #self.label.setText(f"Data inicial: {self.start_date.toString()}")
        elif not self.__end_date:
            self.__end_date = date
            self.highlight_date(self.__end_date, QtGui.QColor("red"))
            #self.label.setText(f"Data inicial: {self.start_date.toString()} \nData final: {self.end_date.toString()}")
        else:
            self.clear_highlight()
            self.__start_date = date
            self.__end_date = None
            self.highlight_date(self.__start_date, QtGui.QColor("green"))
            #self.label.setText(f"Data inicial: {self.start_date.toString()}")
            
    def highlight_date(self, date, color):
        fmt = QtGui.QTextCharFormat()
        fmt.setBackground(color)
        self.Tela0_calendar.setDateTextFormat(date, fmt)

    def clear_highlight(self):
        fmt = QtGui.QTextCharFormat()
        if self.__start_date:#type: ignore
            self.Tela0_calendar.setDateTextFormat(self.__start_date, fmt)
        if self.__end_date:
            self.Tela0_calendar.setDateTextFormat(self.__end_date, fmt)

    def test(self):
        print(self.start_date, end=" Inicio\n")
        print(self.end_date, end=" Final\n")
        print("###################")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    
    ui = Ui_Interface()
    ui.show()
    sys.exit(app.exec_())
