# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_Interface(QtWidgets.QMainWindow):
    def __init__(self, version:str="Beta"):
        self.__version:str = version
        
        super().__init__()
        
        self.setObjectName("Interface")
        
        self.resize(800, 500)
        self.setAnimated(True)
        
        self.setMaximumSize(self.size())
        self.setMinimumSize(self.size())
    
        self.Central = QtWidgets.QWidget(self)
        self.Central.setObjectName("Central")
        
        self.Telas = QtWidgets.QStackedWidget(self.Central)
        self.Telas.setGeometry(self.geometry())
        self.Telas.setObjectName("Telas")
        self.Telas.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.Telas.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
                
        self.Tela0 = QtWidgets.QWidget()
        self.Tela0.setObjectName("Tela0")
        
        self.Telas.addWidget(self.Tela0)
        
        self.Tela1 = QtWidgets.QWidget()
        self.Tela1.setObjectName("Tela1")
        
        self.Tela1_text_movimentacaoDiaria = QtWidgets.QTextEdit(self.Tela1)
        self.Tela1_text_movimentacaoDiaria.setGeometry(QtCore.QRect(150, 30, 131, 41))
        self.Tela1_text_movimentacaoDiaria.setReadOnly(True)
        self.Tela1_text_movimentacaoDiaria.setText("movimentacaoDiaria")
        
        self.pushButton = QtWidgets.QPushButton(self.Tela1)
        self.pushButton.setGeometry(QtCore.QRect(1, 30, 131, 41))
        self.pushButton.setObjectName("pushButton")
        
        self.label = QtWidgets.QLabel(self.Tela1)
        self.label.setGeometry(QtCore.QRect(50, 100, 101, 41))
        self.label.setObjectName("label")
        
        self.Telas.addWidget(self.Tela1)
        self.Telas.setCurrentIndex(1)
        
        self.setCentralWidget(self.Central)
                
        self.menuBar = QtWidgets.QMenuBar(self)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 794, 21))
        self.menuBar.setObjectName("menuBar")
        
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        
        self.menuNew = QtWidgets.QMenu(self.menuFile)
        self.menuNew.setObjectName("menuNew")
        
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        
        self.setMenuBar(self.menuBar)
        
        self.actionQuit = QtWidgets.QAction(self)
        self.actionQuit.setObjectName("actionQuit")
        
        self.actionFile = QtWidgets.QAction(self)
        self.actionFile.setObjectName("actionFile")
        
        self.actionAbout = QtWidgets.QAction(self)
        self.actionAbout.setObjectName("actionAbout")
        
        self.menuNew.addSeparator()
        self.menuNew.addAction(self.actionFile)
        
        self.menuFile.addAction(self.menuNew.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        
        self.menuHelp.addAction(self.actionAbout)
        
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)
        

        
    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Interface", f"Informe de Rendimentos TRM | Versão: {self.__version}"))
        self.pushButton.setText(_translate("Interface", "BT_Exemplo"))
        self.label.setText(_translate("Interface", "Exemplo"))
        self.menuFile.setTitle(_translate("Interface", "Arquivos"))
        self.menuNew.setTitle(_translate("Interface", "New"))
        self.menuHelp.setTitle(_translate("Interface", "Help"))
        self.actionQuit.setText(_translate("Interface", "Quit"))
        self.actionFile.setText(_translate("Interface", "File"))
        self.actionAbout.setText(_translate("Interface", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_Interface()
    ui.show()
    sys.exit(app.exec_())
